### ISSUE TITLE
Ant build fails after commit 917c22b

### ISSUE THREAD

**Issue by jugne** [CompEvol/BeastFX#90]
Hi, after the commit 917c22b I get an ant build error that complains about the static variables:

```
 LogAnalyser.java:671: error: Illegal static declaration in inner class LogAnalyser.CoreRunnable
    static private boolean headerPrinted = false;
    [javac]                                ^
    [javac]   modifier 'static' is only allowed in constant variable declarations
  LogAnalyser.java:672: error: Illegal static declaration in inner class LogAnalyser.CoreRunnable
    [javac]         static private int lineNr = 0;
    [javac]                            ^
    [javac]   modifier 'static' is only allowed in constant variable declarations
```

**Comment by rbouckaert** [comment]
Which javac version are you using? With v17.0.3, I get
```
~$ javac --version
javac 17.0.3
~$ ant cleanBEASTlabs
Buildfile: /Users/remco/workspace/BEASTLabs/build.xml

cleanBEASTlabs:
   [delete] Deleting directory /Users/remco/workspace/BEASTLabs/build

BUILD SUCCESSFUL
Total time: 0 seconds
~$ ant compile-allBEASTlabs
Buildfile: /Users/remco/workspace/BEASTLabs/build.xml

initBEASTlabs:
     [echo] BUILD_BEAST_labs: /Users/remco/workspace/BEASTLabs/build.xml

compile-allBEASTlabs:
     [echo] Classpath = /Users/remco/workspace/BEASTLabs/build:/Users/remco/workspace/BEASTLabs/lib/nashorn-core-15.3.jar:/Users/remco/workspace/beast2/lib/junit/junit-platform-console-standalone-1.8.2.jar:/Users/remco/workspace/beast2/lib/antlr-runtime-4.10.1.jar:/Users/remco/workspace/beast2/lib/beagle.jar:/Users/remco/workspace/beast2/lib/colt.jar:/Users/remco/workspace/beast2/lib/commons-math3-3.6.1-sources.jar:/Users/remco/workspace/beast2/lib/commons-math3-3.6.1.jar:/Users/remco/workspace/beast2/build:/Users/remco/workspace/BeastFX/build
    [mkdir] Created dir: /Users/remco/workspace/BEASTLabs/build
    [javac] Compiling 153 source files to /Users/remco/workspace/BEASTLabs/build
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [echo] Successfully compiled.

BUILD SUCCESSFUL
Total time: 8 seconds
```
so I'm not sure how to replicate the problem.

**Comment by jugne** [comment]
Hi, I have javac 17.0.5. But the problem seems to have been on my end. I had it trying to build any package and they would only build after I removed the static modifiers in those two lines. But after your comment, I did a fresh java+Beast set up and cannot reproduce it any more..

Sorry for wasting your time!!
